version: '3.8'
services:
  notification-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=<enter_senders_email/username_here>
      - SMTP_PASSWORD=<enter_google_app_password_here>
      - SENDER_EMAIL=<enter_senders_email_here>
    networks:
      - cloud-infra

networks:
  cloud-infra:
    external: true
